services:
    alpine:
        profiles: ["alpine"]
        build:
            context: alpine
        ports:
            - 80:80
        depends_on:
            - mysql

    ubuntu:
        profiles: ["ubuntu"]
        build:
            context: ubuntu
        ports:
            - 80:80
        depends_on:
            - mysql

    mysql:
        profiles: ["ubuntu", "alpine"]
        image: mysql:8.0
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - 3306:3306
