name: CI - build headless image

on:
    push:
        branches-ignore:
            - master
        paths:
            - "headless/**"
            - ".github/**"
    pull_request:
        paths:
            - "headless/**"
            - ".github/**"
    schedule:
        - cron: "0 1 * * 6" # Run at 1am every Saturday
    workflow_dispatch: ~

jobs:
    ci-headless:
        strategy:
            fail-fast: false
            matrix:
                sylius_version: [1.11,1.12]
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout Code
                uses: actions/checkout@v3
            -
                name: Install Buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    buildx-version: latest
            -
                name: Build Image
                run: |
                    docker buildx build \
                    --build-arg SYLIUS_VERSION=${{ matrix.sylius_version }} \
                    --no-cache \
                    --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 headless/
