name: CI - test traditional image on Sylius-Standard project

on:
    push:
        branches-ignore:
            - master
        paths:
            - "traditional/**"
            - ".github/**"
    pull_request:
        paths:
            - ".github/**"
            - "traditional/**"
    schedule:
        - cron: "0 1 * * 6" # Run at 1am every Saturday
    workflow_dispatch: ~

jobs:
    run-traditional-ubuntu-app:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout Code
                uses: actions/checkout@v3
            -
                name: Shutdown default MySQL
                run: sudo service mysql stop
            -
                name: Setup MySQL
                run: |
                    cd .github/workflows/traditional && docker compose --profile alpine up -d
            -
                name: Health Check Store
                run: |
                    sleep 20
                    curl -L --fail http://localhost:80 || exit 1

    run-traditional-alpine-app:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout Code
                uses: actions/checkout@v3
            -
                name: Shutdown default MySQL
                run: sudo service mysql stop
            -
                name: Setup MySQL
                run: |
                    cd .github/workflows/traditional && docker compose --profile alpine up -d
            -
                name: Health Check Store
                run: |
                    sleep 20
                    curl -L --fail http://localhost:80 || exit 1
