name: CI - test traditional image on Sylius-Standard project

on:
    push:
        branches-ignore:
            - master
        paths:
            - "traditional/**"
            - ".github/**"
    pull_request:
        paths:
            - ".github/**"
            - "traditional/**"

jobs:
    run-app:
        runs-on: ubuntu-latest

        steps:
            -
                name: checkout code
                uses: actions/checkout@v2
            -
                name: Shutdown default MySQL
                run: sudo service mysql stop
            -
                name: Setup MySQL
                run: |
                    docker network create --driver bridge sylius_network
                    docker run \
                        --platform linux/amd64 \
                        -e MYSQL_ALLOW_EMPTY_PASSWORD=true \
                        -p 3306:3306/tcp \
                        --name mysql \
                        --net sylius_network \
                        -d mysql:5.7
            -
                name: Setup Sylius Store
                run: |
                    docker build \
                        --network sylius_network \
                        --tag sylius-traditional \
                        .github/workflows/

                    docker run \
                        --net sylius_network \
                        -p 80:80/tcp \
                        -d sylius-traditional
            -
                name: Health Check Store
                run: |
                    sleep 10
                    curl -L --fail http://localhost:80 || exit 1
