services:
    app:
        build:
            context: .
        ports:
            - 80:80
        depends_on:
            - mysql
        networks:
            - sylius

    mysql:
        image: mysql:5.7
        platform: linux/amd64
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
            - 3306:3306
        networks:
            - sylius

networks:
    sylius:
        driver: bridge
